init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.11'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - ps: 'node test\test.js #PowerShell'
  - cmd: node test\test.js

cache:
  - node_modules
